name:                Haskercises
version:             0.1.0.0
github:              "fpdevil/Haskercises"
license:             BSD3
author:              "Sampath Singamsetty"
maintainer:          "Singamsetty@Sampath@gmail.com"
copyright:           "(c) 2019"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fpdevil/Haskercises#readme>

dependencies:
- base >= 4.7 && < 5
- time
- containers
- directory
- mtl
- split
- aeson
- aeson-pretty
- bytestring
- text
- random
- QuickCheck


library:
  source-dirs: src

executables:
  Haskercises-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskercises

tests:
  Haskercises-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskercises
